version: '3.7'

services:
  php:
    container_name: phpApp
    env_file:
        - .env
    build:
        context: ./docker/
        dockerfile: Dockerfile
    networks:
        - backend
        - database
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/

  mysql:
    container_name: db_mysql
    image: mysql:8
    networks:
        - database
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: appEmployee
        MYSQL_USER: manager
        MYSQL_PASSWORD: manager_employee

networks:
  backend:
    name: backend
    external: true
  database:
   name: database
   external: true
volumes:
  mysql-data:
