version: '3.7'

services:
  php:
    container_name: phpApp
    env_file:
        - .env
    build:
        context: ./docker/
        dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/

  mysql:
    container_name: db_mysql
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: appEmployee
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql-data:
